# Generated by Django 6.0.6 on 2026-06-19 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                ('address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firma / Korxona nomi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ajratilgan Qarz Limiti')),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Joriy Qarzdorlik')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_limits', to=settings.AUTH_USER_MODEL, verbose_name='Magazinchi (Mijoz)')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_limits', to=settings.AUTH_USER_MODEL, verbose_name='Diler')),
            ],
            options={
                'unique_together': {('dealer', 'client')},
            },
        ),
    ]
