# Generated by Django 6.0.6 on 2026-06-19 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_dealerprofile_creditlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('CAR', 'Mashina'), ('MOTO', 'Motoroller / Skuter'), ('BIKE', 'Velosiped'), ('FOOT', 'Piyoda')], default='CAR', max_length=10, verbose_name='Transport turi')),
                ('is_available', models.BooleanField(default=True, verbose_name="Hozir bo'sh (Ishga tayyor)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
