# Generated by Django 6.0.6 on 2026-06-19 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda (Magazinchi buyurtma berdi)'), ('ACCEPTED', 'Tasdiqlandi (Diler qadoqlayapti)'), ('COURIER_REQUESTED', "Kuryerga so'rov yuborildi"), ('SHIPPED', "Yo'lda (Kuryer yukni oldi)"), ('DELIVERED', 'Yetkazib berildi (Yopildi)'), ('CANCELED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='Buyurtma holati')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Magazinchi to'lagan summa")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Nasiya (Qarz) summa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'COURIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'DEALER'}, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narxi (so'm)")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ombordagi qoldiq soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'DEALER'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Buyurtma paytidagi narxi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product')),
            ],
        ),
    ]
