# Generated by Django 6.0.4 on 2026-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
