# Generated by Django 6.0.6 on 2026-07-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, verbose_name="Savat (to'plam) mahsulotmi"),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='products.product', verbose_name='Savat')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundles', to='products.product', verbose_name='Tarkibidagi mahsulot')),
            ],
            options={
                'verbose_name': 'Savat tarkibi',
                'verbose_name_plural': 'Savat tarkiblari',
                'unique_together': {('bundle', 'component')},
            },
        ),
    ]